FROM python:3.7.4

# setting working dir inside container
WORKDIR /to_do_flask_app

COPY ./requirements.txt ./

# collecting required access creds

ARG USERNAME

ENV USERNAME $USERNAME

ARG PASSWORD

ENV PASSWORD $PASSWORD

ARG HOST

ENV HOST $HOST

ARG DBNAME

ENV DBNAME $DBNAME

ARG USER

ENV USER $USER

ARG PASS

ENV PASS $PASS

RUN env && pip install --no-cache-dir -r requirements.txt

COPY ./app.py ./
COPY ./run.py ./
COPY ./storage.py ./
COPY ./db_user.py ./
COPY ./user.py ./
COPY tests ./tests

CMD ["pytest"]